### ISSUE TITLE
on execute make, linker ld on linux64 fails to find -lblas -llapack -lX11

### ISSUE THREAD

**Issue by chalkie666** [linshaova/CUDA_SIMrecon#2]
[100%] Building CXX object cudaSirecon/CMakeFiles/cudaSireconDriver.dir/cudaSireconDriver.cpp.o
Linking CXX executable cudaSireconDriver
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status
cudaSirecon/CMakeFiles/cudaSireconDriver.dir/build.make:97: recipe for target 'cudaSirecon/cudaSireconDriver' failed
make[2]: *** [cudaSirecon/cudaSireconDriver] Error 1
CMakeFiles/Makefile2:167: recipe for target 'cudaSirecon/CMakeFiles/cudaSireconDriver.dir/all' failed
make[1]: *** [cudaSirecon/CMakeFiles/cudaSireconDriver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

@linshaova 
Failed at the very last step...
So i guess cmake is not setting or finding the locations for those properly on linux 64, 
but does correctl set and find lots of other libs to link. 

best

Dan

**Comment by linshaova** [comment]
I assume you installed blas and lapack development libraries on your Linux? On Fedora, they are named blas-devel and lapack-devel. Same with X11, libX11-devel. I should make this clear in CMakeLists also.

**Comment by chalkie666** [comment]
I dont think I did.... Not the -dev packages! That will do the trick!

Indeed it would be good to state that in the instructions.

Thanks!

**Comment by chalkie666** [comment]
@linshaova 
on ubuntu, i installed 
xorg-dev
liblapack-dev
liblapack3
libopenblas-base
libopenblas-dev

and it compiled without errors.
Thanks!
D

**Comment by chalkie666** [comment]
could add that more explicit into the the instructions i guess....
